# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9aae3923c7fd15ee74b0a8356ce89edb43fc96b8e3431c6dac08017e42496954ef11784950938f17630a217f5cc66e03df413997c4752900abe6ae0706180d5

test:
  secret_key_base: 0f266732fce07ec96daede9d2f743576cac2855115d2f9894d2671287d4b5a749991a6032d23565b9c225a57a1f680ed27896beb4b7c4f8b4e545bef4a88ff03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
